### ISSUE TITLE
Using the updated x86_64-elf-tools and the -m elf_i386 results in a i386:x86-64 architecture of input file `Source/Kernel/kernel.o' is incompatible with i386 output

### ISSUE THREAD

**Issue by TylerJaacks** [lordmilko/VSKernelDev#1]
```D:\Documents\Development\Toolchains\x86_64-elf-tools\bin\x86_64-elf-ld.exe -m elf_i386 -o kernel.bin -Ttext 0x1000 Source/Kernel/kernel_entry.o Source/Kernel/kernel.o --oformat binary
D:\Documents\Development\Toolchains\x86_64-elf-tools\bin\x86_64-elf-ld.exe: i386:x86-64 architecture of input file `Source/Kernel/kernel.o' is incompatible with i386 output```

**Comment by lordmilko** [comment]
I've only tested this with x86 however this is seems like an issue with `ld` rather than `VSKernelDev` specifically

Here is something a quick Google Search turned up

* https://stackoverflow.com/questions/7027018/c-make-error-link-problem-i386x86-64-architecture-of-input-file-incompatibl

You may need to tweak other configuration parameters to compile for x64

Ultimately all VisualGDB is doing is running your makefile, so make sure you can make your project directly
